### ISSUE TITLE
DESCRIPTION: Please add URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [Wancen/airpart#4]
To make it easier to find this repo (e.g. from https://www.bioconductor.org/packages/release/bioc/html/airpart.html), please add:

```
URL: https://github.com/Wancen/airpart
BugReports: https://github.com/Wancen/airpart/issues
```

to your DESCRIPTION file.

**Comment by Wancen** [comment]
Thanks for your advice. Added it!
